# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Wed Apr 05 18:36:13 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: TTT3
spec:
- pattern: DDDD
  stages:
  - stage: New Stage
  - stage: New Stage (1)
