# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Wed Mar 15 19:17:22 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: TTT3
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.V1
    value: !value "xlrelease_PasswordStringVariable_folder_V1_value"
  - type: xlrelease.StringVariable
    key: folder.v2
    value: v2
- name: Test
  type: git.Repository
  url: https://github.com/SivaprasathDigitalAI/sample-test
  username: SivaprasathDigitalAI
  password: !value "git_Repository_Test_password"
- template: T1
  scheduledStartDate: 2023-03-06T09:00:00+05:30
  dueDate: 2023-03-06T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT
      type: xlrelease.Task
  riskProfile: Default risk profile
- name: DB
  type: xlrelease.BlankDashboard
  owner: admin
  tiles:
  - name: Active releases by status
    type: live.ReleasesByStatusTile
    row: 0
    col: 0
    filters:
    - type: xlrelease.DateFilter
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Active releases by status
    type: live.ReleasesByStatusTile
    row: 0
    col: 2
    filters:
    - type: xlrelease.DateFilter
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Avg. release duration
    type: xlrelease.AvgReleaseDurationTile
    row: 0
    col: 4
  - name: Active releases
    type: live.ReleasesTile
    row: 1
    col: 4
    filters:
    - type: xlrelease.DateFilter
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Active releases by status
    type: live.ReleasesByStatusTile
    row: 2
    col: 0
    filters:
    - type: xlrelease.DateFilter
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Avg. task duration
    type: xlrelease.AvgTaskDurationTile
    row: 0
    col: 5
  - name: Avg. release duration over time
    type: xlrelease.AvgReleaseDurationByMonthTile
    row: 3
    col: 2
  - name: Avg. task duration
    type: xlrelease.AvgTaskDurationTile
    row: 2
    col: 2
- notifications:
  - notification: TASK_FLAGGED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The status of the **${task.title}** task in the **${release.title}** release was changed to **${task.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Watcher
    - Release Admin
    - Task Team
  - notification: TASK_OVERDUE
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is overdue.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: MANUAL_TASK_STARTED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started and is assigned to you or your team.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Task Owner
  - notification: TASK_FAILED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has failed.

      Other tasks could still be in progress, but the release will stop after they complete.

      You can retry the task, reassign it to somebody else or abort the release.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: COMMENT_ADDED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      **${comment.authorFullName}** commented on the **${task.title}** task in the **${release.title}** release:

      ${comment.text}
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_FAILED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release has failed due to a task failure.

      The release is now stopped.

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: TASK_DUE_SOON
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is due in **${task.dueInHours}** hours and **${task.dueInMinutes}** minutes.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: ACTIVE_TASK_UNASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is active but not assigned to anyone anymore.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_FAILING
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release is failing due to a task failure.

      Other tasks may still be in progress, but the release will stop after they complete.

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: USER_TOKEN_ABOUT_TO_EXPIRE
    priority: Normal
    subject: "[Release] Your personal access token is about to expire"
    body: |-
      Your personal access token "'${token.tokenNote}'" will expire in about ${token.expirationDurationInHours} hours.

       If this token is still needed, visit [Access tokens](${url}#/personal-access-token) to generate an equivalent.
  - notification: RELEASE_FLAGGED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The status of the **${release.title}** release was changed to **${release.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Release Admin
  - notification: MANUAL_TASK_STARTED_WITHOUT_OWNER
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started, but it is not assigned.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Release Admin
  - notification: RELEASE_COMPLETED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been completed."
    roles:
    - Release Admin
  - notification: TASK_WAITING_FOR_INPUT
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release needs your input.

      Please enter the required information so the release can continue.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_ABORTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been aborted."
    roles:
    - Release Admin
  - notification: RELEASE_STARTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been started."
    roles:
    - Release Admin
  - notification: ACTIVE_TASK_ASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The active task **${task.title}** in the **${release.title}** release is\
      \ now assigned to ${task.ownerFullName}. Testing Assigned Tasks"
    roles:
    - Watcher
    - Task Team
    - Task Owner
---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  home: TTT3
spec:
- directory: "."
  teams:
  - name: Folder Owner
    users:
    - admin
    permissions:
    - folder#edit_variables
    - delivery_pattern#edit
    - folder#edit_configuration
    - delivery#edit
    - folder#view_versions
    - folder#apply_changes
    - group#view
    - folder#edit_versions
    - folder#edit_notifications
    - delivery_pattern#view
    - group#edit
    - delivery#view
    - delivery#edit_tracked_item
    - folder#view
    - folder#edit_security
    - dashboard#edit
    - folder#edit
    - dashboard#view
    - folder#generate_configuration
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#create_release_other_folder
    - template#edit
    - trigger#view_trigger
    - template#lock_task
    - template#view
    - folder#view
    - template#edit_security
    - template#create_release
    - template#edit_triggers
    - template#edit_precondition
    - template#edit_failure_handler
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#edit_precondition
    - release#edit
    - release#advance_task_transition
    - release#edit_security
    - release#restart_phase
    - release#lock_task
    - folder#view
    - release#edit_task_script
    - release#edit_task_configuration_facet
    - release#edit_task_flag
    - release#edit_task_dates
    - release#edit_task
    - release#edit_task_attachments
    - release#task_transition
    - trigger#view_trigger
    - release#reassign_task
    - release#edit_task_input_output_properties
    - release#edit_task_tags
    - release#edit_task_description
    - trigger#edit_trigger
    - release#view
    - release#start
    - release#edit_blackout
    - release#edit_failure_handler
    - release#abort
