# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Wed Mar 08 16:26:26 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: TTT3
spec:
- name: T1
  type: time.Schedule
  releaseTitle: DDDDD
  template: TT2
  periodicity: 0 0 9-17 * * MON-FRI
  enabled: false
