# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Thu Apr 20 19:36:34 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: CleanUp
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.f1
- pattern: P1
  stages:
  - stage: New Stage
  - stage: New Stage (1)
- pattern: P2
  stages:
  - stage: New Stage
  - stage: New Stage (1)
  - stage: New Stage (2)
  - stage: New Stage (3)
- template: T1
  scheduledStartDate: 2023-04-13T09:00:00+05:30
  dueDate: 2023-04-13T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT
      type: xlrelease.Task
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_T1_scriptUserPassword"
  riskProfile: Default risk profile
- template: T2
  scheduledStartDate: 2023-04-20T09:00:00+05:30
  dueDate: 2023-04-20T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: GG
      type: xlrelease.Task
  riskProfile: Default risk profile
- name: Test
  type: xlrelease.BlankDashboard
  owner: admin
  tiles:
  - name: Active releases by status
    type: live.ReleasesByStatusTile
    row: 0
    col: 0
    filters:
    - type: xlrelease.DateFilter
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Avg. task duration
    type: xlrelease.AvgTaskDurationTile
    row: 0
    col: 2
  - name: Active releases
    type: live.ReleasesTile
    row: 0
    col: 3
    filters:
    - type: xlrelease.DateFilter
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Avg. release duration
    type: xlrelease.AvgReleaseDurationTile
    row: 0
    col: 5
  - name: Avg. release duration over time
    type: xlrelease.AvgReleaseDurationByMonthTile
    row: 2
    col: 0
  - name: Avg. task duration
    type: xlrelease.AvgTaskDurationTile
    row: 1
    col: 2
  - name: Completed releases
    type: xlrelease.CompletedReleasesTile
- name: Deployments
  type: xlrelease.DeploymentsByStageDashboard
  owner: admin
  tiles:
  - type: xlrelease.PlaceholderTile
    row: 0
    col: 0
    content: Development
  - name: Current applications
    type: deployment.CurrentApplicationsTile
    width: 1
    height: 1
    row: 1
    col: 0
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Development
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Activity
    type: deployment.DeploymentsActivityTile
    width: 1
    row: 2
    col: 0
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Development
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Total deployments
    type: deployment.TotalDeploymentsTile
    width: 1
    height: 1
    row: 4
    col: 0
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Development
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Deployments
    type: deployment.DeploymentsDistributionTile
    width: 1
    row: 5
    col: 0
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Development
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
    height: 1
  - name: Deployment success rate
    type: deployment.DeploymentsSuccessRateTile
    width: 1
    height: 1
    row: 6
    col: 0
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Development
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - type: xlrelease.PlaceholderTile
    row: 0
    col: 1
    content: Test
  - name: Current applications
    type: deployment.CurrentApplicationsTile
    width: 1
    height: 1
    row: 1
    col: 1
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Test
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Activity
    type: deployment.DeploymentsActivityTile
    width: 1
    row: 2
    col: 1
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Test
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Total deployments
    type: deployment.TotalDeploymentsTile
    width: 1
    height: 1
    row: 4
    col: 1
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Test
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Deployments
    type: deployment.DeploymentsDistributionTile
    width: 1
    row: 5
    col: 1
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Test
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
    height: 1
  - name: Deployment success rate
    type: deployment.DeploymentsSuccessRateTile
    width: 1
    height: 1
    row: 6
    col: 1
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Test
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - type: xlrelease.PlaceholderTile
    row: 0
    col: 2
    content: Acceptance
  - name: Current applications
    type: deployment.CurrentApplicationsTile
    width: 1
    height: 1
    row: 1
    col: 2
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Acceptance
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Activity
    type: deployment.DeploymentsActivityTile
    width: 1
    row: 2
    col: 2
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Acceptance
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Total deployments
    type: deployment.TotalDeploymentsTile
    width: 1
    height: 1
    row: 4
    col: 2
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Acceptance
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Deployments
    type: deployment.DeploymentsDistributionTile
    width: 1
    row: 5
    col: 2
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Acceptance
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
    height: 1
  - name: Deployment success rate
    type: deployment.DeploymentsSuccessRateTile
    width: 1
    height: 1
    row: 6
    col: 2
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Acceptance
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - type: xlrelease.PlaceholderTile
    row: 0
    col: 3
    content: Production
  - name: Current applications
    type: deployment.CurrentApplicationsTile
    width: 1
    height: 1
    row: 1
    col: 3
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Production
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Activity
    type: deployment.DeploymentsActivityTile
    width: 1
    row: 2
    col: 3
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Production
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Total deployments
    type: deployment.TotalDeploymentsTile
    width: 1
    height: 1
    row: 4
    col: 3
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Production
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Deployments
    type: deployment.DeploymentsDistributionTile
    width: 1
    row: 5
    col: 3
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Production
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
    height: 1
  - name: Deployment success rate
    type: deployment.DeploymentsSuccessRateTile
    width: 1
    height: 1
    row: 6
    col: 3
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Production
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  columns: 4
  filters:
  - type: xlrelease.FolderFilter
    folder: ./
  - type: xlrelease.DateFilter
- name: T1
  type: test.TestTrigger
  enabled: false
  periodicity: "150"
  releaseTitle: FFFFF
  template: T1
  releaseFolder: ./
  username: admin
  password: !value "test_TestTrigger_T1_password"
- notifications:
  - notification: TASK_FLAGGED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The status of the **${task.title}** task in the **${release.title}** release was changed to **${task.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Watcher
    - Release Admin
    - Task Team
  - notification: TASK_OVERDUE
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is overdue.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: MANUAL_TASK_STARTED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started and is assigned to you or your team.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Task Owner
  - notification: TASK_FAILED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has failed.

      Other tasks could still be in progress, but the release will stop after they complete.

      You can retry the task, reassign it to somebody else or abort the release.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: COMMENT_ADDED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      **${comment.authorFullName}** commented on the **${task.title}** task in the **${release.title}** release:

      ${comment.text}
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_FAILED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release has failed due to a task failure.

      The release is now stopped.

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: TASK_DUE_SOON
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is due in **${task.dueInHours}** hours and **${task.dueInMinutes}** minutes.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: ACTIVE_TASK_UNASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is active but not assigned to anyone anymore.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_FAILING
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release is failing due to a task failure.

      Other tasks may still be in progress, but the release will stop after they complete.

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: RELEASE_FLAGGED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The status of the **${release.title}** release was changed to **${release.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Release Admin
  - notification: MANUAL_TASK_STARTED_WITHOUT_OWNER
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started, but it is not assigned.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Release Admin
  - notification: RELEASE_COMPLETED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been completed."
    roles:
    - Release Admin
  - notification: TASK_WAITING_FOR_INPUT
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release needs your input.

      Please enter the required information so the release can continue.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_ABORTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been aborted."
    roles:
    - Release Admin
  - notification: RELEASE_STARTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been started."
    roles:
    - Release Admin
  - notification: ACTIVE_TASK_ASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The active task **${task.title}** in the **${release.title}** release is\
      \ now assigned to ${task.ownerFullName}. Test Content Added"
    roles:
    - Watcher
    - Task Team
    - Task Owner
