# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Thu Apr 20 19:33:07 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: CleanUp
spec:
- template: T2
  scheduledStartDate: 2023-04-20T09:00:00+05:30
  dueDate: 2023-04-20T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: GG
      type: xlrelease.Task
  riskProfile: Default risk profile
