# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Wed Dec 29 18:09:50 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-7000
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.password
    value: !value "xlrelease_PasswordStringVariable_folder_password_value"
- name: GIt-Test-Local
  type: git.Repository
  url: http://localhost/root/test-6107
  username: root
  password: !value "git_Repository_GIt_Test_Local_password"
- name: git Another Local
  type: git.Repository
  url: http://localhost/root/test-6107
  username: root
  password: !value "git_Repository_git_Another_Local_password"
- template: Template One
  scheduledStartDate: 2021-12-29T09:00:00+05:30
  dueDate: 2021-12-29T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT
      type: xlrelease.Task
  variables:
  - type: xlrelease.PasswordStringVariable
    key: password
    requiresValue: false
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Template_One_scriptUserPassword"
  riskProfile: Default risk profile
- name: Git Poll Trigger
  type: git.Poll
  releaseTitle: 7000-git
  variables:
  - type: xlrelease.PasswordStringVariable
    key: password
    requiresValue: false
  template: Template One
  releaseFolder: ./
  gitRepository: GIt-Test-Local
  branch: main
  username: root
- name: Time-Test
  type: time.Schedule
  releaseTitle: 7000-Release
  variables:
  - type: xlrelease.PasswordStringVariable
    key: password
    requiresValue: false
  template: Template One
  releaseFolder: ./
  periodicity: 0 0 9-17 * * MON
