# Exported from:        http://LAPTOP-9C20LTLG:5517/
# Release version:      23.3.0
# Date created:         Thu Feb 22 12:32:50 IST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Patterns.yaml
  - Templates.yaml
