# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      23.1.0
# Date created:         Mon Mar 25 17:45:31 IST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Patterns.yaml
  - Templates.yaml
