# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      23.1.0
# Date created:         Mon Mar 25 16:44:20 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: D-33573
spec:
- name: T4
  type: time.Schedule
  releaseTitle: SFFEE
  template: T1-1
  pollType: REPEAT
  periodicity: "125"
  enabled: false
  triggerTime: 2024-03-25T16:33:41.485Z
- name: T5
  type: time.Schedule
  releaseTitle: asswsws
  template: T2
  pollType: REPEAT
  periodicity: "145"
  enabled: false
  triggerTime: 2024-03-25T16:39:08.264000
