# Exported from:        http://LAPTOP-9C20LTLG:5517/
# Release version:      23.3.0-SNAPSHOT
# Date created:         Fri May 26 17:39:12 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Test1
spec:
- pattern: F1
  stages:
  - stage: New Stage
  - stage: New Stage (1)
  - stage: New Stage (2)
