# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      23.4.0-SNAPSHOT
# Date created:         Thu Feb 01 17:30:26 IST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Connections.yaml
  - Dashboards.yaml
  - Notifications.yaml
  - Patterns.yaml
  - Templates.yaml
  - Triggers.yaml
  - Variables.yaml
  - Workflows.yaml
