# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      24.1.0-SNAPSHOT
# Date created:         Fri Feb 23 15:33:03 IST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Permissions.yaml
