# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.16-SNAPSHOT
# Date created:         Thu Mar 30 14:45:38 IST 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: D1
spec:
- template: T1
  scheduledStartDate: 2023-03-30T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT
      type: xlrelease.Task
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_T1_scriptUserPassword"
  riskProfile: Default risk profile
