# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Tue Dec 21 13:42:09 IST 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: ENG-8568
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.Text.One
    value: Text One
  - type: xlrelease.StringVariable
    key: folder.Text Two
    value: Text Two
  - type: xlrelease.PasswordStringVariable
    key: folder.password.one
    label: admin
    value: !value "xlrelease_PasswordStringVariable_folder_password_one_value"
  - type: xlrelease.PasswordStringVariable
    key: folder.password.two
    label: admin
    value: !value "xlrelease_PasswordStringVariable_folder_password_two_value"
  - type: xlrelease.PasswordStringVariable
    key: folder.git.credentials
    value: !value "xlrelease_PasswordStringVariable_folder_git_credentials_value"
- name: test
  type: events.GetWebhookEndpoint
  path: test
  authentication:
    type: events.NoAuthentication
- name: Another Repo
  type: git.Repository
  variableMapping:
    password: "${folder.git.credentials}"
  url: https://github.com/SivaprasathDigitalAI/TestRepo
  username: SivaprasathDigitalAI
- name: Jenkin Server
  type: jenkins.Server
  url: http://localhost:8090
  username: admin
- name: Jenkins2
  type: jenkins.Server
  url: http://localhost:8090
  username: admin
- pattern: Another pattern
  stages:
  - stage: New Stage
- pattern: Pattern One
  stages:
  - stage: Stage One
  - stage: Stage Two
- template: MSSQL Template
  scheduledStartDate: 2021-12-16T09:00:00+05:30
  dueDate: 2021-12-16T10:00:00+05:30
  phases:
  - phase: "8568"
    tasks:
    - name: Test Script
      type: xlrelease.ScriptTask
      script: |-
        print folderVariables['folder.password.one']
        print folderVariables['folder.password.two']
    - name: Task One
      type: xlrelease.Task
    - name: Gate Task
      type: xlrelease.GateTask
    - name: Create Pattern
      type: delivery.CreateDelivery
      ^title: Test
      pattern: ./Pattern One
      folder: ./
    - name: Test WebHook
      type: webhook.WaitForJsonEvent
      endpoint: test
    - name: UInput
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
    color: '#3D6C9E'
  riskProfile: Default risk profile
