# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      24.1.0-SNAPSHOT
# Date created:         Wed Jan 31 11:47:59 IST 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Dashboards.yaml
  - Notifications.yaml
  - Patterns.yaml
  - Permissions.yaml
  - Templates.yaml
  - Triggers.yaml
  - Variables.yaml
  - Workflows.yaml
