# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      24.1.0-SNAPSHOT
# Date created:         Wed Jan 31 11:46:37 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.admin_password
    value: !value "xlrelease_PasswordStringVariable_folder_admin_password_value"
  - type: xlrelease.StringVariable
    key: folder.admin_username
    value: admin
- pattern: P1
  stages:
  - stage: Stage one
  - stage: stage two
  - stage: Stage Three
  autoComplete: true
- pattern: p2
  stages:
  - stage: P2 Stage One
  - stage: P2 Stage Two
  - stage: P3 Stage Three
- template: Template -Base
  scheduledStartDate: 2024-01-31T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT
      type: xlrelease.Task
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Template__Base_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
- template: Work Flow Template
  scheduledStartDate: 2024-01-31T09:00:00+05:30
  phases:
  - phase: Workflow tasks
    tasks:
    - name: WFMT
      type: xlrelease.Task
  kind: WORKFLOW
  disableNotifications: true
  author: admin
  defaultTargetFolder: ./
- name: Custom D1
  type: xlrelease.BlankDashboard
  owner: admin
  tiles:
  - name: Active releases
    type: live.ReleasesTile
    row: 0
    col: 0
    filters:
    - type: xlrelease.DateFilter
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Active releases by risk
    type: live.ReleasesByRiskTile
    row: 0
    col: 2
    filters:
    - type: xlrelease.DateFilter
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Active releases by status
    type: live.ReleasesByStatusTile
    row: 0
    col: 4
    filters:
    - type: xlrelease.DateFilter
    - type: xlrelease.CompositeFilter
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
  - name: Getting started
    type: xlrelease.AnnouncementTile
    row: 2
    col: 0
  - name: Avg. release duration over time
    type: xlrelease.AvgReleaseDurationByMonthTile
    row: 2
    col: 3
  - name: Avg. task duration
    type: xlrelease.AvgTaskDurationTile
    row: 4
    col: 0
  - name: Completed releases
    type: xlrelease.CompletedReleasesTile
    row: 4
    col: 1
  - name: Deployment success rate
    type: deployment.DeploymentsSuccessRateTile
    row: 4
    col: 2
    filters:
    - type: xlrelease.DateFilter
  - name: Longest task type
    type: xlrelease.LongestTaskTypeTile
    row: 4
    col: 3
- name: Deployments
  type: xlrelease.DeploymentsByStageDashboard
  owner: admin
  tiles:
  - type: xlrelease.PlaceholderTile
    row: 0
    col: 0
    content: Development
  - name: Current applications
    type: deployment.CurrentApplicationsTile
    width: 1
    height: 1
    row: 1
    col: 0
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Development
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Activity
    type: deployment.DeploymentsActivityTile
    width: 1
    row: 2
    col: 0
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Development
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Total deployments
    type: deployment.TotalDeploymentsTile
    width: 1
    height: 1
    row: 4
    col: 0
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Development
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Deployments
    type: deployment.DeploymentsDistributionTile
    width: 1
    row: 5
    col: 0
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Development
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
    height: 1
  - name: Deployment success rate
    type: deployment.DeploymentsSuccessRateTile
    width: 1
    height: 1
    row: 6
    col: 0
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Development
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - type: xlrelease.PlaceholderTile
    row: 0
    col: 1
    content: Test
  - name: Current applications
    type: deployment.CurrentApplicationsTile
    width: 1
    height: 1
    row: 1
    col: 1
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Test
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Activity
    type: deployment.DeploymentsActivityTile
    width: 1
    row: 2
    col: 1
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Test
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Total deployments
    type: deployment.TotalDeploymentsTile
    width: 1
    height: 1
    row: 4
    col: 1
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Test
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Deployments
    type: deployment.DeploymentsDistributionTile
    width: 1
    row: 5
    col: 1
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Test
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
    height: 1
  - name: Deployment success rate
    type: deployment.DeploymentsSuccessRateTile
    width: 1
    height: 1
    row: 6
    col: 1
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Test
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - type: xlrelease.PlaceholderTile
    row: 0
    col: 2
    content: Acceptance
  - name: Current applications
    type: deployment.CurrentApplicationsTile
    width: 1
    height: 1
    row: 1
    col: 2
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Acceptance
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Activity
    type: deployment.DeploymentsActivityTile
    width: 1
    row: 2
    col: 2
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Acceptance
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Total deployments
    type: deployment.TotalDeploymentsTile
    width: 1
    height: 1
    row: 4
    col: 2
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Acceptance
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Deployments
    type: deployment.DeploymentsDistributionTile
    width: 1
    row: 5
    col: 2
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Acceptance
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
    height: 1
  - name: Deployment success rate
    type: deployment.DeploymentsSuccessRateTile
    width: 1
    height: 1
    row: 6
    col: 2
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Acceptance
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - type: xlrelease.PlaceholderTile
    row: 0
    col: 3
    content: Production
  - name: Current applications
    type: deployment.CurrentApplicationsTile
    width: 1
    height: 1
    row: 1
    col: 3
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Production
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Activity
    type: deployment.DeploymentsActivityTile
    width: 1
    row: 2
    col: 3
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Production
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Total deployments
    type: deployment.TotalDeploymentsTile
    width: 1
    height: 1
    row: 4
    col: 3
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Production
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  - name: Deployments
    type: deployment.DeploymentsDistributionTile
    width: 1
    row: 5
    col: 3
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Production
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
    height: 1
  - name: Deployment success rate
    type: deployment.DeploymentsSuccessRateTile
    width: 1
    height: 1
    row: 6
    col: 3
    filters:
    - type: xlrelease.EnvironmentStageFilter
      stage: Production
    - type: xlrelease.FolderFilter
      folder: ./
    - type: xlrelease.DateFilter
  columns: 4
  filters:
  - type: xlrelease.FolderFilter
    folder: ./
  - type: xlrelease.DateFilter
- name: Trigger One
  type: time.Schedule
  releaseTitle: "D-25848_${triggerTime}"
  template: Template -Base
  tags:
  - Dummy Trigger tag
  releaseFolder: ./
  pollType: REPEAT
  periodicity: "90"
  enabled: false
  triggerTime: 2024-01-31T11:43:15.043000
- notifications:
  - notification: TASK_FLAGGED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The status of the **${task.title}** task in the **${release.title}** release was changed to **${task.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Watcher
    - Release Admin
    - Task Team
  - notification: TASK_OVERDUE
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is overdue.

      After the task is completed, please mark it as Completed in Release. ANother Dummy Content
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: MANUAL_TASK_STARTED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started and is assigned to you or your team.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Task Owner
  - notification: TASK_FAILED
    priority: High
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has failed.

      Other tasks could still be in progress, but the release will stop after they complete.

      You can retry the task, reassign it to somebody else or abort the release.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: COMMENT_ADDED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      **${comment.authorFullName}** commented on the **${task.title}** task in the **${release.title}** release:

      ${comment.text}
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_FAILED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release has failed due to a task failure.

      The release is now stopped.

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: TASK_DUE_SOON
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is due in **${task.dueInHours}** hours and **${task.dueInMinutes}** minutes.

      After the task is completed, please mark it as Completed in Release.
    roles:
    - Watcher
    - Release Admin
    - Task Owner
  - notification: ACTIVE_TASK_UNASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release is active but not assigned to anyone anymore.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_FAILING
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The **${release.title}** release is failing due to a task failure.

      Other tasks may still be in progress, but the release will stop after they complete.

      You can retry the failed task, reassign it to somebody else or abort the release.
    roles:
    - Release Admin
  - notification: RELEASE_FLAGGED
    priority: High
    subject: "[Release] ${release.title}"
    body: |-
      The status of the **${release.title}** release was changed to **${release.flagStatus}** with the following comment:

      **${release.flagComment}**
    roles:
    - Release Admin
  - notification: MANUAL_TASK_STARTED_WITHOUT_OWNER
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release has started, but it is not assigned.

      Please assign the task to a user or a team.
    roles:
    - Watcher
    - Release Admin
  - notification: RELEASE_COMPLETED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been completed."
    roles:
    - Release Admin
  - notification: TASK_WAITING_FOR_INPUT
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: |-
      The **${task.title}** task in the **${release.title}** release needs your input.

      Please enter the required information so the release can continue. Dummy content
    roles:
    - Watcher
    - Task Team
    - Task Owner
  - notification: RELEASE_ABORTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been aborted."
    roles:
    - Release Admin
  - notification: RELEASE_STARTED
    priority: Normal
    subject: "[Release] ${release.title}"
    body: "The **${release.title}** release has been started."
    roles:
    - Release Admin
  - notification: ACTIVE_TASK_ASSIGNED
    priority: Normal
    subject: "[Release] ${release.title}: ${task.title}"
    body: "The active task **${task.title}** in the **${release.title}** release is\
      \ now assigned to ${task.ownerFullName}."
    roles:
    - Watcher
    - Task Team
    - Task Owner
---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  path: /
spec:
- directory: "."
  teams:
  - name: Template Owner
    roles:
    - Tester3
    users:
    - admin
    permissions:
    - template#create_release_other_folder
    - template#edit
    - trigger#view_trigger
    - template#lock_task
    - template#view
    - app_pipelines#view
    - folder#view
    - template#create_release
    - template#edit_precondition
    - template#edit_failure_handler
  - name: Folder Owner
    roles:
    - Tester1
    users:
    - admin
    permissions:
    - folder#edit_variables
    - delivery_pattern#edit
    - folder#edit_configuration
    - app_pipelines#view
    - delivery#edit
    - folder#view_versions
    - folder#apply_changes
    - group#view
    - folder#edit_versions
    - folder#edit_notifications
    - app_pipelines#edit
    - delivery_pattern#view
    - group#edit
    - delivery#view
    - delivery#edit_tracked_item
    - folder#view
    - folder#edit_security
    - dashboard#edit
    - folder#edit
    - dashboard#view
    - folder#generate_configuration
  - name: Release Admin
    roles:
    - Tester2
    users:
    - admin
    permissions:
    - release#edit_precondition
    - release#edit
    - workflow#view_execution
    - release#advance_task_transition
    - workflow#abort_execution
    - release#restart_phase
    - release#lock_task
    - folder#view
    - release#edit_task_script
    - release#edit_task_flag
    - release#edit_task_configuration_facet
    - release#edit_task_dates
    - workflow#start_execution
    - release#edit_task
    - release#edit_task_attachments
    - release#task_transition
    - trigger#view_trigger
    - release#reassign_task
    - app_pipelines#view
    - release#edit_task_input_output_properties
    - release#edit_task_tags
    - release#edit_task_description
    - trigger#edit_trigger
    - release#view
    - release#edit_blackout
    - release#start
    - release#edit_failure_handler
    - release#abort
