# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      24.1.0-319.113
# Date created:         Tue Mar 19 19:19:27 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: S-106906
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.child_username
    value: admin
  - type: xlrelease.PasswordStringVariable
    key: folder.child_password
    value: !value "xlrelease_PasswordStringVariable_folder_child_password_value"
- pattern: Pattern-1
  stages:
  - stage: Pattern-1-1
  - stage: Pattern-1-2
  - stage: Pattern-1-3
  trackedItems:
  - trackedItem: Track-1-1
  - trackedItem: Track1-2
- pattern: Pattern-2
  stages:
  - stage: New Stage
  - stage: New Stage (1)
  - stage: New Stage (2)
- template: App_config
  scheduledStartDate: 2024-03-19T09:00:00+05:30
  dueDate: 2024-03-19T10:00:00+05:30
  phases:
  - phase: Workflow tasks
    tasks:
    - name: MT1
      type: xlrelease.Task
  kind: WORKFLOW
  categories:
  - Application Life Cycle Management
  disableNotifications: true
  author: admin
  defaultTargetFolder: ./
- template: Template-1
  scheduledStartDate: 2024-03-19T09:00:00+05:30
  dueDate: 2024-03-19T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT
      type: xlrelease.Task
    - name: Js
      type: xlrelease.ScriptTask
    - name: CRT
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: FFFFF
      releaseTags:
      - ddddd
      template: ./Template-2
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Template_1_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
- template: Template-2
  scheduledStartDate: 2024-03-19T09:00:00+05:30
  dueDate: 2024-03-19T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT-1-2
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: admin
- name: Trigger-1
  type: time.Schedule
  releaseTitle: "Trigger-1_release-${triggerTime}"
  template: Template-1
  releaseFolder: ./
  pollType: REPEAT
  periodicity: "90"
  enabled: false
- directory: Child
  children:
  - template: Child_Template_1
    scheduledStartDate: 2024-03-19T09:00:00+05:30
    dueDate: 2024-03-19T10:00:00+05:30
    phases:
    - phase: New Phase
      tasks:
      - name: Mt_child
        type: xlrelease.Task
    scriptUsername: "${folder.child_username}"
    variableMapping:
      scriptUserPassword: "${folder.child_password}"
    riskProfile: Default risk profile
    author: admin
  - directory: Grandchild
