# Exported from:        http://LAPTOP-9C20LTLG:5516/
# Release version:      23.1.0
# Date created:         Fri Mar 22 13:33:46 IST 2024

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: S-106906
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.child_password
  - type: xlrelease.StringVariable
    key: folder.child_username
    value: admin
- pattern: Pattern-1
  stages:
  - stage: Pattern-1-1
  - stage: Pattern-1-2
  - stage: Pattern-1-3
  trackedItems:
  - trackedItem: Track-1-1
  - trackedItem: Track1-2
- pattern: Pattern-2
  stages:
  - stage: New Stage
  - stage: New Stage (1)
  - stage: New Stage (2)
- template: App_config
  scheduledStartDate: 2024-03-19T09:00:00+05:30
  dueDate: 2024-03-19T10:00:00+05:30
  phases:
  - phase: Workflow tasks
    tasks:
    - name: MT1
      type: xlrelease.Task
  kind: WORKFLOW
  categories:
  - Application Life Cycle Management
  disableNotifications: true
  author: admin
  defaultTargetFolder: ./
- template: Template-1
  scheduledStartDate: 2024-03-19T09:00:00+05:30
  dueDate: 2024-03-19T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT
      type: xlrelease.Task
    - name: Js
      type: xlrelease.ScriptTask
  scriptUsername: admin
  riskProfile: Default risk profile
  author: admin
- template: Template-2
  scheduledStartDate: 2024-03-19T09:00:00+05:30
  dueDate: 2024-03-19T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: MT-1-2
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: admin
- name: "1"
  type: time.Schedule
  releaseTitle: w1
  template: Template-1
  pollType: REPEAT
  periodicity: "123"
  enabled: false
  triggerTime: 2024-03-22T13:33:11.537000
- name: "2"
  type: time.Schedule
  releaseTitle: 2wer
  template: Template-2
  pollType: REPEAT
  periodicity: "145"
  enabled: false
  triggerTime: 2024-03-22T13:33:30.976000
- directory: Child
  children:
  - template: Child_Template_1
    scheduledStartDate: 2024-03-19T09:00:00+05:30
    dueDate: 2024-03-19T10:00:00+05:30
    phases:
    - phase: New Phase
      tasks:
      - name: Mt_child
        type: xlrelease.Task
    scriptUsername: "${folder.child_username}"
    variableMapping:
      scriptUserPassword: "${folder.child_password}"
    riskProfile: Default risk profile
    author: admin
  - name: Child Release statistics
    type: xlrelease.ReleaseStatisticsDashboard
    owner: admin
    tiles:
    - name: Longest task type
      type: xlrelease.LongestTaskTypeTile
      row: 0
      col: 1
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    - name: Number of releases
      type: xlrelease.ReleasesByMonthTile
      row: 2
      col: 3
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    - name: Release efficiency
      type: xlrelease.ReleaseEfficiencyTile
      row: 2
      col: 0
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    - name: Avg. task duration
      type: xlrelease.AvgTaskDurationTile
      row: 1
      col: 1
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    - name: Time spent by task category
      type: xlrelease.TaskTimeSpentTile
      row: 0
      col: 4
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    - name: Completed releases
      type: xlrelease.CompletedReleasesTile
      row: 0
      col: 0
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    - name: Avg. release duration
      type: xlrelease.AvgReleaseDurationTile
      row: 1
      col: 0
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    - name: Task efficiency
      type: xlrelease.TaskEfficiencyTile
      row: 0
      col: 2
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    - name: Top 10 longest releases
      type: xlrelease.LongestReleasesTile
      row: 4
      col: 0
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    - name: Avg. release duration over time
      type: xlrelease.AvgReleaseDurationByMonthTile
      row: 4
      col: 3
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    - name: Top 10 longest phases
      type: xlrelease.LongestPhasesTile
      row: 6
      col: 0
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    - name: Top 10 longest tasks
      type: xlrelease.LongestTasksTile
      row: 6
      col: 3
      filters:
      - type: xlrelease.FolderFilter
        folder: ./Child
      - type: xlrelease.DateFilter
    filters:
    - type: xlrelease.FolderFilter
      folder: ./Child
    - type: xlrelease.DateFilter
  - directory: Grandchild
  - directory: Grandchild-2
  - directory: child-2
    children:
    - directory: grandChild
